In [1]:
import numpy as np
from sklearn.naive_bayes import CategoricalNB
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
data_BreastCancer=pd.read_csv("C:\\Users\\Masoumeh\\BreastCancer DataSet\\breast-cancer.data")
data_BreastCancer

,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no.1
0,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
2,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
3,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
4,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
...,...,...,...,...,...,...,...,...,...,...
280,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
281,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
282,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
283,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
284,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [29]:
data_BreastCancer["30-39"].value_counts()

50-59    96
40-49    90
60-69    57
30-39    35
70-79     6
20-29     1
Name: 30-39, dtype: int64

In [4]:
data_BreastCancer["30-39"]=data_BreastCancer["30-39"].astype("category").cat.codes
data_BreastCancer["30-39"]

0      2
1      2
2      4
3      2
4      4
      ..
280    1
281    1
282    4
283    2
284    3
Name: 30-39, Length: 285, dtype: int8

In [30]:
data_BreastCancer.columns=['Class','age','menopause','tumor-size','inv-nodes','node-caps','deg-malig','breast','breast-quad','irradiat']

In [31]:
data_BreastCancer

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
2,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
3,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
4,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no
...,...,...,...,...,...,...,...,...,...,...
280,recurrence-events,30-39,premeno,30-34,0-2,no,2,left,left_up,no
281,recurrence-events,30-39,premeno,20-24,0-2,no,3,left,left_up,yes
282,recurrence-events,60-69,ge40,20-24,0-2,no,1,right,left_up,no
283,recurrence-events,40-49,ge40,30-34,3-5,no,3,left,left_low,no
284,recurrence-events,50-59,ge40,30-34,3-5,no,3,left,left_low,no

In [1]:
for col in data_BreastCancer.columns:
    data_BreastCancer[col]=data_BreastCancer[col].astype("category").cat.codes

data_BreastCancer

NameError: name 'data_BreastCancer' is not defined

In [22]:
data_BreastCancer.head()

,Class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,0,2,2,3,0,1,1,1,5,0
1,0,2,2,3,0,1,1,0,2,0
2,0,4,0,2,0,1,1,1,3,0
3,0,2,2,0,0,1,1,1,4,0
4,0,4,0,2,0,1,1,0,2,0

In [23]:
data_BreastCancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Class        285 non-null    int8
 1   age          285 non-null    int8
 2   menopause    285 non-null    int8
 3   tumor-size   285 non-null    int8
 4   inv-nodes    285 non-null    int8
 5   node-caps    285 non-null    int8
 6   deg-malig    285 non-null    int8
 7   breast       285 non-null    int8
 8   breast-quad  285 non-null    int8
 9   irradiat     285 non-null    int8
dtypes: int8(10)
memory usage: 2.9 KB

In [34]:
from sklearn.model_selection import train_test_split
#x=data_BreastCancer
y=data_BreastCancer["irradiat"]
x=data_BreastCancer.drop("irradiat", axis=1)

In [2]:
import seaborn as sns
for col in data_BreastCancer.columns:
    
    sns.catplot(x='age', y="irradiat", hue=str(col), kind="boxen",jitter=Tre,data=data_BreastCancer)

NameError: name 'data_BreastCancer' is not defined

In [35]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state=10)

In [38]:
x_test.shape

(86, 9)

In [39]:
from sklearn.naive_bayes import CategoricalNB
nb_classifier=CategoricalNB()

In [40]:
nb_classifier.fit(x_train, y_train)

CategoricalNB()

In [41]:
y_prediction=nb_classifier.predict(x_test)

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

           0       0.86      0.87      0.86        68
           1       0.47      0.44      0.46        18

    accuracy                           0.78        86
   macro avg       0.66      0.66      0.66        86
weighted avg       0.77      0.78      0.78        86

In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_prediction)

array([[59,  9],
       [10,  8]], dtype=int64)