<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6 color=#F32500>
        <div  align=center>
            تمرین هفته دوم بوت کمپ یادگیری ماشین-
            مپصا
        </div>
        <br/>
    </font>
</div>

<div style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<div align=center>
			<font face="IranNastaliq" size=5>    
                  چون عهده نمی‌شود کسی فردا را
                <br><br>
                 حالی خوش دار این دل پر سودا را
                <br><br>
                می نوش به ماهتاب ای ماه که ماه
                <br><br>
                بسیار بتابد و نیابد ما را        			   	
                <p></p>
			</font>
        </div>
    </font>
</div>

In [1]:
import numpy as np
import pandas as pd

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال اول:‌
            </font>
        <font>
            مجموعه داده های زیر را در نظر بگیرید
        </font>
        <br/>
    </font>
</div>

In [2]:
numbers = np.array([ 4.5 , 7.8 ,  6.5,  0.5,  8. ,  6.5, 19. , 13.5,  2.5, 17. , 19. ,
       19.5, 13. ,  12.21 ,  6.3 ,  0.5,  9.5, 13.5, 16. ,  2.5, 10.5,  8. ,
       10. , 15.5,  7.5,  0. ,  1. , 10.5,  2. , 11. ,  3. , 14. ,  3.5,
       18.5, 13. ,  1. , 14.5, 15. ,  1.52 , 15.5,  1.5,  2.8 ,  3.5,  6.5,
        12.5, 14.5, 11.5,  8. ,  10.2 ,  5.5,  0.5, 23. ,  5. ,  0.5, 17.5,
       17.5, 17.5, 15. ,  4.5, 17. , 18. , 10. ,  8.5, 14. , 18.5, 19.5,
       16.3 ,  8.5,  0. ,  9.5,  6. ,  2. ,  5. ,  9.5,  4. ,  4. ,  1. ,
        8. , 18.5, 18. , 15.5,  4.5,  1.5, 20. ,  0.5, 19. ,  4. ,  9.5,
       12.8  ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<p></p>
        برای این مجموعه داده ها قصد داریم با دو فرمول زیر مقادیر آنها را تغییر دهیم:
<br>
۱. اگر عددی کمتر از هشت و نیم است با فرمول زیر آن عدد تغییر کند:
<br>
$$ y = 10 + \frac{x}{10} $$
<br>
۲. اگر عددیبیشتر یا مساوی هشت و نیم است با فرمول زیر آن عدد تغییر کند :
<br>
$$ y =  -0.0051x^{2} + 0.8586x + 3.4332 $$
<br>
توجه کنید که حتی بعد از تغییر باید بیشینه عدد نهایتا بیشینه عدد موجود در داده فعلی باشد. 25 درصد داده های بزرگتر را در آرایه زیر بریزید
</div>

In [3]:
len_numbers=numbers.size
temp=np.zeros(len_numbers)
for count in range(len_numbers):
    if numbers[count]<8.5:
        num=10+(numbers[count]/10)
        if num < numbers[count]:
            temp[count]=num
        else:
            temp[count]=numbers[count]
    else:
        num=(-0.0051*(numbers[count]**2))+(0.8586*numbers[count])+3.4332
        if num < numbers[count]:
            temp[count]=num
        else:
            temp[count]=numbers[count]
numbers_v2=temp.copy()
numbers_v2

array([ 4.5     ,  7.8     ,  6.5     ,  0.5     ,  8.      ,  6.5     ,
       17.9055  , 13.5     ,  2.5     , 16.5555  , 17.9055  , 18.236625,
       13.      , 12.21    ,  6.3     ,  0.5     ,  9.5     , 13.5     ,
       15.8652  ,  2.5     , 10.5     ,  8.      , 10.      , 15.5     ,
        7.5     ,  0.      ,  1.      , 10.5     ,  2.      , 11.      ,
        3.      , 14.      ,  3.5     , 17.571825, 13.      ,  1.      ,
       14.5     , 15.      ,  1.52    , 15.5     ,  1.5     ,  2.8     ,
        3.5     ,  6.5     , 12.5     , 14.5     , 11.5     ,  8.      ,
       10.2     ,  5.5     ,  0.5     , 20.4831  ,  5.      ,  0.5     ,
       16.896825, 16.896825, 16.896825, 15.      ,  4.5     , 16.5555  ,
       17.2356  , 10.      ,  8.5     , 14.      , 17.571825, 18.236625,
       16.073361,  8.5     ,  0.      ,  9.5     ,  6.      ,  2.      ,
        5.      ,  9.5     ,  4.      ,  4.      ,  1.      ,  8.      ,
       17.571825, 17.2356  , 15.5     ,  4.5     ,  1.5     , 18.5652  ,
        0.5     , 17.9055  ,  4.      ,  9.5     , 12.8     ])

In [4]:
#top_new_twenty_five = 
temp=np.sort(temp)
print(temp)
quarter=int(len_numbers*0.25)
top_new_twenty_five = temp[:(3*quarter):-1]
top_new_twenty_five=np.sort(top_new_twenty_five)
top_new_twenty_five

[ 0.        0.        0.5       0.5       0.5       0.5       0.5
  1.        1.        1.        1.5       1.5       1.52      2.
  2.        2.5       2.5       2.8       3.        3.5       3.5
  4.        4.        4.        4.5       4.5       4.5       5.
  5.        5.5       6.        6.3       6.5       6.5       6.5
  7.5       7.8       8.        8.        8.        8.        8.5
  8.5       9.5       9.5       9.5       9.5      10.       10.
 10.2      10.5      10.5      11.       11.5      12.21     12.5
 12.8      13.       13.       13.5      13.5      14.       14.
 14.5      14.5      15.       15.       15.5      15.5      15.5
 15.8652   16.073361 16.5555   16.5555   16.896825 16.896825 16.896825
 17.2356   17.2356   17.571825 17.571825 17.571825 17.9055   17.9055
 17.9055   18.236625 18.236625 18.5652   20.4831  ]

array([15.5     , 15.5     , 15.5     , 15.8652  , 16.073361, 16.5555  ,
       16.5555  , 16.896825, 16.896825, 16.896825, 17.2356  , 17.2356  ,
       17.571825, 17.571825, 17.571825, 17.9055  , 17.9055  , 17.9055  ,
       18.236625, 18.236625, 18.5652  , 20.4831  ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<p></p>
 25 درصد داده های کوچکتر آرایه اول را در آرایه زیر بریزید
</div>

In [5]:
#down_old_twenty_five = 
down_old_twenty_five = temp[:quarter]
down_old_twenty_five

array([0.  , 0.  , 0.5 , 0.5 , 0.5 , 0.5 , 0.5 , 1.  , 1.  , 1.  , 1.5 ,
       1.5 , 1.52, 2.  , 2.  , 2.5 , 2.5 , 2.8 , 3.  , 3.5 , 3.5 , 4.  ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
      <p></p>
        داده های متناظر دو آرایه به دست آمده را از یکدیگر کسر کنید و در یک آرایه سه بعدی که اندازه ابعاد سوم و دوم آن یک میباشد بریزید
</div>

In [6]:
#TODO
result=(top_new_twenty_five-down_old_twenty_five).reshape(quarter,1,1)
result

array([[[15.5     ]],

       [[15.5     ]],

       [[15.      ]],

       [[15.3652  ]],

       [[15.573361]],

       [[16.0555  ]],

       [[16.0555  ]],

       [[15.896825]],

       [[15.896825]],

       [[15.896825]],

       [[15.7356  ]],

       [[15.7356  ]],

       [[16.051825]],

       [[15.571825]],

       [[15.571825]],

       [[15.4055  ]],

       [[15.4055  ]],

       [[15.1055  ]],

       [[15.236625]],

       [[14.736625]],

       [[15.0652  ]],

       [[16.4831  ]]])

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال دوم:‌
        </font>
در این تمرین قصد داریم به تحلیل داده های فیلم های برتر سینمای جهان به معیار imdb بپردازیم. ابتدا دادههای مربوط به فیلم را از فایل csv فراخوانی میکنیم
        <br/>
    </font>
</div>

In [19]:
movies = pd.read_csv("data/imdb_movie_rank.csv")
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [20]:
movies.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        در این دیتاست اگر داده ای وجود دارد که مقدار nullدارد سطرش را حذف کنید. 
        <br/>
    </font>
</div>

In [21]:
#TODO
print(movies.shape)
movies=movies.dropna(inplace = False, axis=0)
print(movies.shape)

(979, 6)
(976, 6)

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        فیلم ها را براساس مدت زمان فیلم به صورت نزولی مرتب کنید و پنجاه تای اول را در فایل csv با نام long_time ذخیره کنید 
        <br/>
    </font>
</div>

In [22]:
#TODO
movies=movies.sort_values('duration',ignore_index=True)
long_time=movies.iloc[:50,:]
long_time

,star_rating,title,content_rating,genre,duration,actors_list
0,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
1,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
2,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"[u'Werner Krauss', u'Conrad Veidt', u'Friedric..."
3,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
4,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
5,7.6,Following,R,Mystery,69,"[u'Jeremy Theobald', u'Alex Haw', u'Lucy Russe..."
6,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']"
7,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
8,7.4,Alice in Wonderland,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
9,8.0,The Nightmare Before Christmas,PG,Animation,76,"[u'Danny Elfman', u'Chris Sarandon', u""Catheri..."
10,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
11,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
12,7.8,The Triplets of Belleville,PG-13,Animation,78,"[u'Mich\xe8le Caucheteux', u'Jean-Claude Donda..."
13,7.8,Zelig,PG,Comedy,79,"[u'Woody Allen', u'Mia Farrow', u'Patrick Horg..."
14,7.5,L'illusionniste,PG,Animation,80,"[u'Jean-Claude Donda', u'Eilidh Rankin', u'Dun..."
15,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
16,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
17,8.1,Before Sunset,R,Drama,80,"[u'Ethan Hawke', u'Julie Delpy', u'Vernon Dobt..."
18,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
19,7.7,The Dinner Game,PG-13,Comedy,80,"[u'Thierry Lhermitte', u'Jacques Villeret', u'..."
20,8.0,Nosferatu,UNRATED,Horror,81,"[u'Max Schreck', u'Greta Schr\xf6der', u'Ruth ..."
21,7.6,Ice Age,PG,Animation,81,"[u'Denis Leary', u'John Leguizamo', u'Ray Roma..."
22,7.8,South Park: Bigger Longer & Uncut,R,Animation,81,"[u'Trey Parker', u'Matt Stone', u'Mary Kay Ber..."
23,7.6,Army of Darkness,R,Comedy,81,"[u'Bruce Campbell', u'Embeth Davidtz', u'Marcu..."
24,8.3,Toy Story,G,Animation,81,"[u'Tom Hanks', u'Tim Allen', u'Don Rickles']"
25,7.7,The Purple Rose of Cairo,PG,Comedy,82,"[u'Mia Farrow', u'Jeff Daniels', u'Danny Aiello']"
26,8.0,This Is Spinal Tap,R,Comedy,82,"[u'Rob Reiner', u'Michael McKean', u'Christoph..."
27,7.5,The Texas Chain Saw Massacre,R,Horror,83,"[u'Marilyn Burns', u'Edwin Neal', u'Allen Danz..."
28,7.6,The Little Mermaid,G,Animation,83,"[u'Jodi Benson', u'Samuel E. Wright', u'Rene A..."
29,8.0,Ghost in the Shell,NOT RATED,Animation,83,"[u'Atsuko Tanaka', u'Iemasa Kayumi', u'Akio \x..."
30,8.2,Persona,NOT RATED,Drama,83,"[u'Bibi Andersson', u'Liv Ullmann', u'Margaret..."
31,7.6,Robin Hood,G,Animation,83,"[u'Brian Bedford', u'Phil Harris', u'Roger Mil..."
32,8.1,Beauty and the Beast,G,Animation,84,"[u""Paige O'Hara"", u'Robby Benson', u'Richard W..."
33,7.8,Evil Dead II,X,Comedy,84,"[u'Bruce Campbell', u'Sarah Berry', u'Dan Hicks']"
34,7.5,Pi,R,Drama,84,"[u'Sean Gullette', u'Mark Margolis', u'Ben She..."
35,7.6,The Evil Dead,NC-17,Horror,85,"[u'Bruce Campbell', u'Ellen Sandweiss', u'Rich..."
36,7.9,Once,R,Drama,85,"[u'Glen Hansard', u'Mark\xe9ta Irglov\xe1', u'..."
37,7.5,Fruitvale Station,R,Biography,85,"[u'Michael B. Jordan', u'Melonie Diaz', u'Octa..."
38,7.7,The Muppet Christmas Carol,G,Comedy,85,"[u'Michael Caine', u'Dave Goelz', u'Steve Whit..."
39,8.1,High Noon,PG,Western,85,"[u'Gary Cooper', u'Grace Kelly', u'Thomas Mitc..."
40,7.6,The Curse of the Were-Rabbit,G,Animation,85,"[u'Peter Sallis', u'Helena Bonham Carter', u'R..."
41,7.6,Dracula,APPROVED,Horror,85,"[u'Bela Lugosi', u'Helen Chandler', u'David Ma..."
42,8.1,The Killing,APPROVED,Crime,85,"[u'Sterling Hayden', u'Coleen Gray', u'Vince E..."
43,7.6,The Naked Gun: From the Files of Police Squad!,PG-13,Comedy,85,"[u'Leslie Nielsen', u'Priscilla Presley', u'O...."
44,7.9,The 39 Steps,UNRATED,Mystery,86,"[u'Robert Donat', u'Madeleine Carroll', u'Luci..."
45,8.0,The Iron Giant,PG,Animation,86,"[u'Eli Marienthal', u'Harry Connick Jr.', u'Je..."
46,8.3,My Neighbor Totoro,G,Animation,86,"[u'Hitoshi Takagi', u'Noriko Hidaka', u'Chika ..."
47,7.4,Frances Ha,R,Comedy,86,"[u'Greta Gerwig', u'Mickey Sumner', u'Adam Dri..."
48,8.6,Modern Times,G,Comedy,87,"[u'Charles Chaplin', u'Paulette Goddard', u'He..."
49,7.7,A Hard Day's Night,APPROVED,Comedy,87,"[u'John Lennon', u'Paul McCartney', u'George H..."

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         تابعی بنویسید که نام بازیگر را به عنوان آرگومان بگیرد و تعداد فیلم های برتر از این لیست را که بازی کرده محاسبه کند.
        <br/>
    </font>
</div>

In [23]:
#TODO
def count_moveis(name,long_time):
    count=0
    for movie_actors in long_time['actors_list']:
        if name in movie_actors:
            count+=1
    return count
actor_name=input("Enter actor name: ")
count_moveis(actor_name,long_time)

Enter actor name: Charles Chaplin

2

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         میانگین امتیاز فیلم ها را براساس ژانر نمایش به دست آورید.
        <br/>
    </font>
</div>

In [24]:
#TODO
movies.groupby(['genre']).star_rating.mean()

genre
Action       7.885926
Adventure    7.940541
Animation    7.914516
Biography    7.857895
Comedy       7.822436
Crime        7.916935
Drama        7.902518
Family       7.850000
Fantasy      7.700000
Film-Noir    8.033333
History      8.000000
Horror       7.806897
Mystery      7.975000
Sci-Fi       7.920000
Thriller     7.680000
Western      8.255556
Name: star_rating, dtype: float64

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
       ستونی به این داده ها اضافه کنید که در صورت اینکه یک فیلم مدت نمایش آن 150 دقیقه و یا بیشتر بود مقدار صفر و در غیر اینصورت 1 در هر سطر این ستون قرار گیرد. دیتافریم حاصل را در یک فایل csv ذخیره کنید.
        <br/>
    </font>
</div>

In [30]:
#TODO
x = pd.DataFrame(movies[movies['duration']>=150])
y = pd.DataFrame(movies[movies['duration']<150])
x['check_duration']=0
y['check_duration']=1
movie=pd.concat([x,y],ignore_index=True)
movie.to_csv("data/imdb_movie_rank_new.csv",index=False)
movie.head(10)

,star_rating,title,content_rating,genre,duration,actors_list,check_duration
0,8.5,The Pianist,R,Biography,150,"[u'Adrien Brody', u'Thomas Kretschmann', u'Fra...",0
1,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ...",0
2,7.8,The Dirty Dozen,NOT RATED,Action,150,"[u'Lee Marvin', u'Ernest Borgnine', u'Charles ...",0
3,7.7,Sophie's Choice,R,Drama,150,"[u'Meryl Streep', u'Kevin Kline', u'Peter MacN...",0
4,8.1,The Raid 2,R,Action,150,"[u'Iko Uwais', u'Yayan Ruhian', u'Arifin Putra']",0
5,8.3,Barfi!,NOT RATED,Adventure,151,"[u'Ranbir Kapoor', u'Priyanka Chopra', u'Ileana']",0
6,8.5,The Departed,R,Crime,151,"[u'Leonardo DiCaprio', u'Matt Damon', u'Jack N...",0
7,8.1,Papillon,R,Biography,151,"[u'Steve McQueen', u'Dustin Hoffman', u'Victor...",0
8,7.8,Ray,PG-13,Biography,152,"[u'Jamie Foxx', u'Regina King', u'Kerry Washin...",0
9,7.5,Harry Potter and the Sorcerer's Stone,PG,Adventure,152,"[u'Daniel Radcliffe', u'Rupert Grint', u'Richa...",0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        عنوان ستونها را به نحوی تغییر دهید که در ستون های دارای _(آندرلاین) فاصله قرار گیرد. به عنوان مثال star_rating به star rating تبدیل می شود.
        <br/>
    </font>
</div>

In [31]:
#TODO
movie.columns
movie.columns = movies.columns.str.replace('_', ' ')
movie

,star rating,title,content rating,genre,duration,actors list,check duration
0,8.5,The Pianist,R,Biography,150,"[u'Adrien Brody', u'Thomas Kretschmann', u'Fra...",0
1,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ...",0
2,7.8,The Dirty Dozen,NOT RATED,Action,150,"[u'Lee Marvin', u'Ernest Borgnine', u'Charles ...",0
3,7.7,Sophie's Choice,R,Drama,150,"[u'Meryl Streep', u'Kevin Kline', u'Peter MacN...",0
4,8.1,The Raid 2,R,Action,150,"[u'Iko Uwais', u'Yayan Ruhian', u'Arifin Putra']",0
...,...,...,...,...,...,...,...
971,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...",1
972,7.5,Biutiful,R,Drama,148,"[u'Javier Bardem', u'Maricel \xc1lvarez', u'Ha...",1
973,8.2,Into the Wild,R,Adventure,148,"[u'Emile Hirsch', u'Vince Vaughn', u'Catherine...",1
974,8.4,Das Boot,R,Adventure,149,"[u'J\xfcrgen Prochnow', u'Herbert Gr\xf6nemeye...",1
975,8.2,Gone Girl,R,Drama,149,"[u'Ben Affleck', u'Rosamund Pike', u'Neil Patr...",1

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        داده ها را براساس ژانر گروه بندی و مرتب کنید و از هر ژانر صرفا سه تای برتر را نمایش دهید
        <br/>
    </font>
</div>

In [32]:
#TODO
tenp=movies.sort_values('star_rating',ascending=False).groupby('genre').head(3)
tenp.sort_values('genre',ascending=False)

,star_rating,title,content_rating,genre,duration,actors_list,check_duration
933,8.6,Once Upon a Time in the West,PG-13,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia...",-1
896,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...",-1
911,8.5,Django Unchained,R,Western,165,"[u'Jamie Foxx', u'Christoph Waltz', u'Leonardo...",-1
538,7.6,La piel que habito,R,Thriller,120,"[u'Antonio Banderas', u'Elena Anaya', u'Jan Co...",-1
320,7.8,Misery,R,Thriller,107,"[u'James Caan', u'Kathy Bates', u'Richard Farn...",-1
329,8.0,Shadow of a Doubt,APPROVED,Thriller,108,"[u'Teresa Wright', u'Joseph Cotten', u'Macdona...",-1
85,7.9,Gravity,PG-13,Sci-Fi,91,"[u'Sandra Bullock', u'George Clooney', u'Ed Ha...",-1
719,8.0,Brazil,R,Sci-Fi,132,"[u'Jonathan Pryce', u'Kim Greist', u'Robert De...",-1
488,8.2,Blade Runner,R,Sci-Fi,117,"[u'Harrison Ford', u'Rutger Hauer', u'Sean You...",-1
653,8.4,Vertigo,APPROVED,Mystery,128,"[u'James Stewart', u'Kim Novak', u'Barbara Bel...",-1
430,8.5,Memento,R,Mystery,113,"[u'Guy Pearce', u'Carrie-Anne Moss', u'Joe Pan...",-1
408,8.6,Rear Window,APPROVED,Mystery,112,"[u'James Stewart', u'Grace Kelly', u'Wendell C...",-1
831,8.5,The Shining,R,Horror,146,"[u'Jack Nicholson', u'Shelley Duvall', u'Danny...",-1
490,8.5,Alien,R,Horror,117,"[u'Sigourney Weaver', u'Tom Skerritt', u'John ...",-1
350,8.6,Psycho,R,Horror,109,"[u'Anthony Perkins', u'Janet Leigh', u'Vera Mi...",-1
1,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G...",-1
373,7.7,Spellbound,UNRATED,Film-Noir,111,"[u'Ingrid Bergman', u'Gregory Peck', u'Michael...",-1
55,8.1,Laura,APPROVED,Film-Noir,88,"[u'Gene Tierney', u'Dana Andrews', u'Clifton W...",-1
103,8.3,The Third Man,NOT RATED,Film-Noir,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va...",-1
386,7.7,The City of Lost Children,R,Fantasy,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ...",-1
203,7.8,Willy Wonka & the Chocolate Factory,G,Family,100,"[u'Gene Wilder', u'Jack Albertson', u'Peter Os...",-1
451,7.9,E.T. the Extra-Terrestrial,PG,Family,115,"[u'Henry Thomas', u'Drew Barrymore', u'Peter C...",-1
140,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...",-1
785,8.9,Fight Club,R,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh...",-1
806,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']",-1
809,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",-1
964,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",-1
935,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",-1
48,8.6,Modern Times,G,Comedy,87,"[u'Charles Chaplin', u'Paulette Goddard', u'He...",-1
50,8.6,City Lights,PASSED,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F...",-1
466,8.6,Life Is Beautiful,PG-13,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G...",-1
961,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...",-1
837,8.7,Goodfellas,R,Biography,146,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']",-1
401,8.6,The Intouchables,R,Biography,112,"[u'Fran\xe7ois Cluzet', u'Omar Sy', u'Anne Le ...",-1
614,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy...",-1
66,8.5,The Lion King,G,Animation,89,"[u'Matthew Broderick', u'Jeremy Irons', u'Jame...",-1
65,8.5,Grave of the Fireflies,UNRATED,Animation,89,"[u'Tsutomu Tatsumi', u'Ayano Shiraishi', u'Ake...",-1
965,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...",-1
937,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl...",-1
942,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort...",-1
858,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E...",-1
843,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'...",-1
594,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi...",-1

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال سوم:‌
        </font>
        تفاوت بین متد read_table و read_csv در ماژول pandas چیست؟
        <br/>
    </font>
</div>

<div dir = "rtl" style="direction:rtl;line-height:150%;">
	<font face="XB Zar" size=3>
        <font color=green size=4>
           پاسخ: 
        </font>
    برای خواندن فایل های csv  از توابع  read_csv  یا read_table در pandas استفاده می شود. این دو تابع تفاوت چندانی با یکدیگر ندارند فقط delimiter در  read_csv  یک کاراکتر کاما  و در  تابع  read_table یک  t\ است.
        <br/>
    </font>
</div>

In [33]:
"""
To read the csv file as pandas.DataFrame, use the pandas function read_csv() or read_table().
The difference between read_csv() and read_table() is almost nothing. 
In fact, the same function is called by the source:
read_csv() delimiter is a comma character
read_table() is a delimiter of tab \t.

"""
read_table=pd.read_table("data/imdb_movie_rank.csv",delimiter=',')
read_table

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال چهارم:‌
        </font>
       توضیح دهید crosstab در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟
        <br/>
    </font>
</div>

<div dir = "rtl" style="direction:rtl;line-height:150%;">
	<font face="XB Zar" size=3>
         <font color=green size=4>
           پاسخ: 
        </font>
       تابع crosstab برای خلاصه سازی سریع داده ها بکار می رود. این تابع یک جدول cross-tabulation (جدول بندی متقاطع) می سازد که می تواند فراوانی ظاهر شدن گروه های خاصی از داده ها را نشان دهد.  
        <br/>
    </font>
</div>

![Minion](https://cdn-dafil.nitrocdn.com/PlqjxCaHlJsZbMQTgjhfGqfTgaqIVbWR/assets/static/optimized/wp-content/uploads/2020/08/33d0d16a61c97c1cd8d1c05b92cd406f.Screen-Shot-2020-08-17-at-7.43.21-AM-1024x466.png)

In [34]:
pd.crosstab(movies.genre, movies.content_rating)

content_rating,APPROVED,G,GP,NC-17,NOT RATED,PASSED,PG,PG-13,R,TV-MA,UNRATED,X
genre,,,,,,,,,,,,
Action,3,1,1,0,4,1,11,44,67,0,3,0
Adventure,3,2,0,0,5,1,21,23,17,0,2,0
Animation,3,20,0,0,3,0,25,5,5,0,1,0
Biography,1,2,1,0,1,0,6,29,36,0,0,0
Comedy,9,2,1,1,16,3,23,23,73,0,4,1
Crime,6,0,0,1,7,1,6,4,87,0,11,1
Drama,12,3,0,4,24,1,25,55,143,1,9,1
Family,0,1,0,0,0,0,1,0,0,0,0,0
Fantasy,0,0,0,0,0,0,0,0,1,0,0,0
Film-Noir,1,0,0,0,1,0,0,0,0,0,1,0
History,0,0,0,0,0,0,0,0,0,0,1,0
Horror,2,0,0,1,1,0,1,2,16,0,5,1
Mystery,4,1,0,0,1,0,1,2,6,0,1,0
Sci-Fi,1,0,0,0,0,0,0,1,3,0,0,0
Thriller,1,0,0,0,0,0,1,0,3,0,0,0
Western,1,0,0,0,2,0,2,1,3,0,0,0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال پنچم:‌
        </font>
         توضیح دهید متد corr در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟ 
        <br/>
    </font>
</div>

<div dir = "rtl" style="direction:rtl;line-height:150%;">
    <font face="XB Zar" size=3>
        <font color=green size=4>
           پاسخ: 
        </font>
        تابع corr برای یافتن همبستگی دو به دو همه ستون ها در دیتافریم (dataframe) استفاده می شود. هر مقدار na به طور خودکار حذف می شود. همچنین ستون هایی با نوع داده غیرعددی در دیتافریم نیز نادیده گرفته می شود. همبستگی متغیر با خودش 1 است. 
        <br/>
    </font>
</div>

In [35]:
movies.corr()

                star_rating  duration  check_duration
star_rating         1.00000   0.22941             NaN
duration            0.22941   1.00000             NaN
check_duration          NaN       NaN             NaN

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال سوم:‌
        </font>
        با استفاده از متد value_counts تعداد فیلمها در هر ریت محتوا را به دست آورید.
        <br/>
    </font>
</div>

In [36]:
# find the value counts
movies.content_rating.value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
PASSED         7
NC-17          7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال ششم:‌
        </font>
        با استفاده از متد sample هفتاد و پنج درصد سطرها را در یک متغیر به نام sample_1 بریزید. درنهایت با استفاده از متد drop از دیتافریم اصلی این سطرها را حذف و دیتافریم جدید را در sample_2 بریزید
        <br/>
    </font>
</div>

In [37]:
sample_1=movies.sample(n=int(movies.shape[0]*0.75), random_state=1)
sample_1

,star_rating,title,content_rating,genre,duration,actors_list,check_duration
931,8.1,La Dolce Vita,NOT RATED,Comedy,174,"[u'Marcello Mastroianni', u'Anita Ekberg', u'A...",-1
724,8.1,In the Name of the Father,R,Biography,133,"[u'Daniel Day-Lewis', u'Pete Postlethwaite', u...",-1
525,7.8,The Experiment,R,Drama,120,"[u'Moritz Bleibtreu', u'Christian Berkel', u'O...",-1
6,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']",-1
248,7.7,Dazed and Confused,R,Comedy,102,"[u'Jason London', u'Wiley Wiggins', u'Matthew ...",-1
...,...,...,...,...,...,...,...
169,8.0,Three Colors: Blue,R,Drama,98,"[u'Juliette Binoche', u'Zbigniew Zamachowski',...",-1
591,8.1,Sin City,R,Crime,124,"[u'Mickey Rourke', u'Clive Owen', u'Bruce Will...",-1
946,8.0,Dances with Wolves,PG-13,Adventure,181,"[u'Kevin Costner', u'Mary McDonnell', u'Graham...",-1
596,8.1,Castle in the Sky,PG,Animation,124,"[u'Anna Paquin', u'James Van Der Beek', u'Clor...",-1
520,7.7,Dangerous Liaisons,R,Drama,119,"[u'Glenn Close', u'John Malkovich', u'Michelle...",-1

In [38]:
sample_2=movies.drop(list(sample_1.index), axis=0)
sample_2

,star_rating,title,content_rating,genre,duration,actors_list,check_duration
7,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin...",-1
10,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P...",-1
15,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran...",-1
20,8.0,Nosferatu,UNRATED,Horror,81,"[u'Max Schreck', u'Greta Schr\xf6der', u'Ruth ...",-1
21,7.6,Ice Age,PG,Animation,81,"[u'Denis Leary', u'John Leguizamo', u'Ray Roma...",-1
...,...,...,...,...,...,...,...
953,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin...",-1
960,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill...",-1
961,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...",-1
969,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe...",-1
970,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony...",-1

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال هفتم:‌
        </font>
         متد pivot_table چه عملکردی دارد؟
        <br/>
    </font>
</div>

<div dir = "rtl" style="direction:rtl;line-height:150%;">
    <font face="XB Zar" size=3>
        <font color=green size=4>
           پاسخ: 
        </font>
        تابع pivot_table یک جدول محوری (pivot) به سبک صفحه گسترده (spreadsheet-style) به عنوان یک دیتافریم ایجاد می کند. سطوح موجود در جدول محوری در اشیاء MultiIndex (اندیس های سلسله مراتبی) در اندیس و ستون های دیتافریم نتیجه ذخیره می شوند.
        <br/>
    </font>
</div>

![Minion](pivot_table.png)